# AutoGen代理配置文件
# 定义各种代理的配置参数

# GitHub数据获取代理配置
github_agent:
  name: "GitHubAgent"
  description: "负责从GitHub获取仓库数据"
  config:
    api_token: "${GITHUB_TOKEN}"  # 从环境变量获取
    rate_limit:
      requests_per_hour: 5000
      retry_delay: 60  # 秒
    cache:
      enabled: true
      ttl: 3600  # 缓存时间（秒）

# 代码分析代理配置
code_analysis_agent:
  name: "CodeAnalysisAgent"
  description: "负责代码分析和分块处理"
  config:
    supported_languages:
      - python
      - javascript
      - typescript
      - java
      - cpp
      - go
      - rust
    chunk_size:
      max_tokens: 1000
      overlap: 100
    tree_sitter:
      parser_timeout: 30  # 秒

# 代理协调器配置
coordinator:
  name: "AgentCoordinator"
  description: "协调各代理间的工作流程"
  config:
    max_concurrent_agents: 5
    message_timeout: 300  # 秒
    retry_attempts: 3
    health_check_interval: 60  # 秒

# 消息总线配置
message_bus:
  type: "async"
  config:
    max_queue_size: 1000
    message_ttl: 3600  # 秒
    dead_letter_queue: true