# 应用主配置文件
# 包含应用级别的配置参数

# 应用基本信息
app:
  name: "Starship"
  version: "1.0.0"
  description: "AI GitHub Knowledge Engine"
  environment: "development"  # development, staging, production

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8501  # Streamlit默认端口
  debug: true
  auto_reload: true

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      enabled: true
      level: "INFO"
    file:
      enabled: true
      level: "DEBUG"
      filename: "logs/starship.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5

# GitHub集成配置
github:
  api_base_url: "https://api.github.com"
  timeout: 30  # 秒
  max_retries: 3
  retry_delay: 1  # 秒
  user_agent: "Starship-AI-Engine/1.0.0"

# 健康度评估配置
health_scoring:
  weights:
    activity: 0.3      # 活跃度权重
    quality: 0.25      # 质量权重
    community: 0.25    # 社区权重
    maintenance: 0.2   # 维护权重
  thresholds:
    excellent: 80      # 优秀阈值
    good: 60          # 良好阈值
    fair: 40          # 一般阈值
    poor: 20          # 较差阈值
  filters:
    min_stars: 10
    min_forks: 5
    max_age_days: 1825  # 5年
    exclude_archived: true
    exclude_private: true

# RAG搜索配置
rag_search:
  retrieval:
    top_k: 10
    similarity_threshold: 0.7
    rerank: true
  generation:
    model: "deepseek-chat"
    max_tokens: 1000
    temperature: 0.1
    stream: true
  prompt_templates:
    search_template: |
      Based on the following GitHub repositories and code snippets, provide a comprehensive answer to the user's question.
      
      Context:
      {context}
      
      Question: {question}
      
      Answer:

# 缓存配置
cache:
  enabled: true
  backend: "memory"  # memory, redis, file
  ttl: 3600  # 默认缓存时间（秒）
  max_size: 1000  # 最大缓存条目数

# 安全配置
security:
  api_key_required: false
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_size: 20
  cors:
    enabled: true
    origins: ["*"]
    methods: ["GET", "POST", "PUT", "DELETE"]
    headers: ["*"]